services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - dinacom-net
    restart: on-failure
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: dinacom-db
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dinacom-net

  redis:
    image: redis:alpine
    container_name: dinacom-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dinacom-net

volumes:
  db_data:

networks:
  dinacom-net:
    driver: bridge